"""Build a portable, offline comparison viewer from recorded pipeline PNGs."""
from pathlib import Path
import base64,json,argparse
p=argparse.ArgumentParser();p.add_argument('root',type=Path);a=p.parse_args();root=a.root.resolve()
def url(path,mime='image/png'):
 return f'data:{mime};base64,'+base64.b64encode(Path(path).read_bytes()).decode()
def dataset(case,fr):
 app=root/case/fr; report=json.loads((app/'report.json').read_text());variants=[]
 for key,label in [('default','현재 · 기본 GIF 마무리'),('rgba','현재 · RGBA'),('repaired','현재 · RGBA + RIFE')]:
  d=app/key;proc=json.loads((d/'processing.json').read_text());paths=sorted((d/'final-preview').glob('frame-*.png'));frames=proc['frames'];sel=proc['selection']
  variants.append(dict(id='current-'+key,label=label,images=[url(f) for f in paths],duration=sum(f['durationMs'] for f in frames),start=sel['startFrame'],sourceIndices=[f['sourceFrameIndex'] for f in frames],notes=f"원본 {sel['startFrame']}–{sel['endFrame']-1} · 64×128 · "+'PNG 기준 비교'))
 for key,label in [('auto','최신 · 자동 선택 + RIFE'),('no-repair','최신 · 자동 선택 · 보정 끄기'),('fixed','최신 · 현재와 같은 구간'),('aligned32','최신 · 32프레임 정합')]:
  d=root/case/'upstream'/key/'review'
  if not (d/'manifest.json').exists():continue
  m=json.loads((d/'manifest.json').read_text());variant=dict(id='latest-'+key,label=label,images=[url(f) for f in m['frames']],duration=m['totalMs'],start=m['sourceStart'],sourceIndices=list(range(m['sourceStart'],m['sourceStart']+len(m['frames']))),notes=f"원본 시작 {m['sourceStart']} · 투명 여백만 64×128로 통일")
  if key=='aligned32':variant.update(sourceIndices=[],notes='32프레임 / 1,333ms · 시작 발 정합 · 별도 처리 실험')
  variants.append(variant)
 if case=='existing':
  for key,label in [('frame-room','동일 입력 RIFE · 현재'),('upstream','동일 입력 RIFE · 최신')]:
   d=root/'shared-rife'/key;meta=json.loads((d/'walk.strip.json').read_text());from PIL import Image
   strip=Image.open(d/'walk.strip.png').convert('RGBA');data=[]
   for i in range(meta['frames']):
    im=strip.crop((i*meta['w'],0,(i+1)*meta['w'],meta['h']));cell=Image.new('RGBA',(64,128));cell.alpha_composite(im,((64-im.width)//2,118-im.height));import io
    buf=io.BytesIO();cell.save(buf,format='PNG');data.append('data:image/png;base64,'+base64.b64encode(buf.getvalue()).decode())
   variants.append(dict(id='rife-'+key,label=label,images=data,duration=1167,start=41,sourceIndices=[],notes='동일한 28장 → 32장 · 같은 RIFE 모델 · 위상 회전 없음'))
 source=Path(report['sources']['clip']['path']);ref=Path(report['sources']['reference']['path'])
 return dict(id=case,title='기존 문제 영상' if case=='existing' else '새 베이스 · 새 Grok 영상',variants=variants,video=url(source,'video/mp4'),base=url(ref),videoHash=report['sources']['clip']['sha256'])
data=[dataset('existing','frame-room/run-02'),dataset('new','frame-room')]
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>프레임룸 · v2.34 실제 비교</title><style>
*{box-sizing:border-box}body{margin:0;background:#101318;color:#edf0f5;font:15px/1.55 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:28px}h1{font-size:26px;margin:0 0 8px}p{color:#b8c2d0;margin:8px 0}button,select{font:inherit;color:#eaf0f8;background:#26313f;border:1px solid #4c596a;border-radius:7px;padding:8px 12px;cursor:pointer}button:hover{background:#38495e}button:focus-visible,select:focus-visible,input:focus-visible{outline:3px solid #91bcff;outline-offset:3px}.bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:20px 0}.bar input{flex:1;min-width:180px;accent-color:#7aa7f4}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.card{background:#1a212b;border:1px solid #354052;border-radius:12px;overflow:hidden}.card select{width:calc(100% - 20px);margin:10px}.stage{display:flex;justify-content:center;background:var(--bg,#d8dce3);padding:16px 0;position:relative;min-height:420px}canvas{image-rendering:pixelated;width:192px;height:384px}.caption{padding:12px;font-size:13px;color:#c3cedc;min-height:100px}.caption strong{display:block;font-size:15px;color:#fff}.legend{border-left:3px solid #759ee0;padding:8px 14px;background:#1b2533}.raw{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:24px 0}.raw video{width:100%;max-height:420px;background:#202632}.raw img{height:230px;max-width:100%;object-fit:contain}.evidence{background:#1b2533;padding:16px;border-radius:8px}.small{font-size:12px;word-break:break-all}.badge{color:#a3e5ba}#status{min-width:120px}details{margin-top:18px}a{color:#a9cbff}@media(max-width:850px){.cards{grid-template-columns:1fr}.raw{grid-template-columns:1fr}main{padding:16px}}
</style><main><p class="badge">동일 MP4 입력 · 오프라인 비교 자료 · 2026-10-06</p><h1>프레임룸과 최신 스킬, 실제 결과 비교</h1><p>새 GPT 베이스 1장 / Grok Pro 영상 1회. 기존 영상은 재사용했습니다. 아래 그림은 실제 처리 결과 PNG이며 브라우저에서는 확대만 합니다.</p><div class="bar"><label>비교 영상 <select id="case"></select></label><button id="fair">같은 구간 비교</button><button id="defaults">자동 처리 비교</button><button id="rife">동일 입력 RIFE 비교</button><label>배경 <select id="bg"><option value="#d8dce3">회색</option><option value="#ffffff">흰색</option><option value="#101010">검정</option></select></label></div><p class="legend" id="condition"></p><div class="bar"><button id="play">재생</button><button id="prev">이전 프레임</button><button id="next">다음 프레임</button><input id="scrub" type="range" min="0" max="999" value="0" aria-label="주기 진행률"><span id="status"></span><label>속도 <select id="speed"><option value="1">1배</option><option value="0.25">0.25배</option></select></label></div><div class="cards" id="cards"></div><div class="raw"><section><h2>Grok 원본 MP4</h2><video id="video" controls muted playsinline></video><button id="seek">왼쪽 결과의 원본 프레임 보기</button><p class="small" id="hash"></p></section><section class="evidence"><h2>두 처리 경로가 공유한 기준 이미지</h2><img id="base" alt="Grok 영상 생성에 사용한 기준 이미지"><p>현재 기본 모드는 GIF 색상 마무리이며, RGBA와 축소 방식도 다릅니다. 최신 결과에는 확대·축소 없이 투명 여백만 추가했습니다.</p><p>서로 다른 자동 선택 구간은 자세가 같은 시점이 아닙니다. 같은 구간 비교 또는 동일 입력 RIFE 비교로 원인을 분리해서 보세요.</p><p>WebP는 설치 문제가 아니라 숨은 RGB의 인코딩 차이입니다. 보이는 색·알파·시간은 같고 exact 인코더로 엄격 검증도 통과했습니다. PNG 품질 비교와 분리합니다. 새 영상의 2프레임 그림 유지와 시작 발 미확정도 보고서에 남겼습니다. 사용자 프로젝트의 승인·편집 상태는 변경하지 않았습니다.</p></section></div><details><summary>비교 해석과 한계</summary><p>재생은 왼쪽 결과의 실제 주기 시간에 맞춰 같은 진행률로 나란히 보여줍니다. 각 결과 고유 시간은 카드에 표시됩니다. 32프레임 정합은 별도 1,333ms 결과이므로 원래 주기와 속도가 다릅니다. 색상·알파 비교의 기준은 PNG이며 GIF는 손실 형식입니다. RIFE 판정 수치는 알고리즘의 진단이며 사람의 품질 승인을 대신하지 않습니다. 이 자료는 프롬프트 A/B나 여러 번 생성한 통계 실험이 아닙니다.</p></details></main><script>const DATA=__DATA__;
let current=DATA[0],selected=[],playing=false,phase=0,last=0,loaded=[];
const $=s=>document.querySelector(s);$('#case').innerHTML=DATA.map(d=>`<option value="${d.id}">${d.title}</option>`).join('');
async function drawSetup(ids){playing=false;$('#play').textContent='재생';selected=ids.map(id=>current.variants.find(v=>v.id===id)||current.variants[0]);$('#cards').innerHTML=selected.map((v,i)=>`<article class="card"><select aria-label="${i+1}번째 비교 결과" data-slot="${i}">${current.variants.map(o=>`<option value="${o.id}" ${o.id===v.id?'selected':''}>${o.label}</option>`).join('')}</select><div class="stage"><canvas width="64" height="128" aria-label="${v.label} 프레임"></canvas></div><div class="caption"></div></article>`).join('');
 loaded=await Promise.all(selected.map(v=>Promise.all(v.images.map(src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})))));window.reviewReady=true;phase=0;render();
 document.querySelectorAll('[data-slot]').forEach(el=>el.onchange=()=>{const ids=selected.map(v=>v.id);ids[Number(el.dataset.slot)]=el.value;drawSetup(ids)});}
function render(){if(!loaded.length)return;document.querySelectorAll('.card').forEach((card,i)=>{const v=selected[i],k=Math.min(v.images.length-1,Math.floor(phase*v.images.length));const ctx=card.querySelector('canvas').getContext('2d');ctx.clearRect(0,0,64,128);ctx.drawImage(loaded[i][k],0,0);card.querySelector('.caption').innerHTML=`<strong>${v.label}</strong>${k+1} / ${v.images.length}장 · ${v.duration}ms<br>${v.notes}`});$('#scrub').value=Math.round(phase*999);$('#status').textContent=`${(phase*100).toFixed(1)}%`;window.reviewState={case:current.id,phase,selected:selected.map(v=>v.id),frames:selected.map(v=>Math.floor(phase*v.images.length))};}
function mode(kind){let ids;if(kind==='fair'){ids=['current-default','current-rgba','latest-fixed'];$('#condition').textContent='같은 구간 · RIFE 끄기: 현재 GIF 마무리 / 현재 RGBA / 최신 고정 구간. 최신 고정 구간에는 엔진의 기존 작은 점 제거 단계가 포함됩니다.'}else if(kind==='rife'&&current.id==='existing'){ids=['rife-frame-room','rife-upstream','latest-fixed'];$('#condition').textContent='같은 28장 입력을 32장으로 보간. 왼쪽: 현재 모두 채택 / 가운데: 최신 8장 거절 후 가까운 원본 선택 / 오른쪽: 보간 전 28장.'}else{ids=['current-default','current-repaired','latest-auto'];$('#condition').textContent='자동 처리 비교: 기존 영상은 현재 시작 41 / 최신 시작 26, 새 영상은 양쪽 시작 17. 보정 수·선택 구간·앵커 차이가 함께 포함됩니다.'}return drawSetup(ids)}
function change(){current=DATA.find(d=>d.id===$('#case').value);$('#video').src=current.video;$('#base').src=current.base;$('#hash').textContent='MP4 SHA-256 '+current.videoHash;$('#rife').disabled=current.id!=='existing';mode('fair')}
$('#case').onchange=change;$('#fair').onclick=()=>mode('fair');$('#defaults').onclick=()=>mode('auto');$('#rife').onclick=()=>mode('rife');$('#bg').onchange=()=>document.documentElement.style.setProperty('--bg',$('#bg').value);$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'일시정지':'재생';last=0};$('#scrub').oninput=()=>{playing=false;$('#play').textContent='재생';phase=Number($('#scrub').value)/1000;render()};function step(d){playing=false;$('#play').textContent='재생';const n=selected[0].images.length;phase=((Math.floor(phase*n)+d+n)%n)/n;render()}$('#prev').onclick=()=>step(-1);$('#next').onclick=()=>step(1);$('#seek').onclick=()=>{const v=selected[0],i=Math.floor(phase*v.images.length);if(v.sourceIndices.length){$('#video').pause();$('#video').currentTime=v.sourceIndices[i]/24}};
function tick(now){if(playing&&last&&loaded.length){phase=(phase+(now-last)/selected[0].duration*Number($('#speed').value))%1;render()}last=now;requestAnimationFrame(tick)}change();requestAnimationFrame(tick);
</script></html>'''
(root/'review.html').write_text(html.replace('__DATA__',json.dumps(data,ensure_ascii=False)),encoding='utf-8');print(root/'review.html')
