import {defaultTransform,type Snapshot,type Occurrence,type Runtime} from './types';
const images=new Map<string,Promise<HTMLImageElement>>();
export function loadImage(url:string){let p=images.get(url);if(!p){p=new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>{images.delete(url);reject(new Error('이미지를 읽지 못했습니다. 자료 연결을 확인해 주세요.'));};i.src=url;});images.set(url,p);}return p;}
export async function drawOccurrence(s:Snapshot,o:Occurrence,outline=true):Promise<HTMLCanvasElement>{
 const f=s.frames.find(f=>f.frameVersionId===o.frameVersionId);if(!f)throw new Error('후보 이미지가 없습니다.');const a=s.assets.find(a=>a.assetId===f.imageAssetId);if(!a)throw new Error('후보 원본을 찾지 못했습니다.');const g=s.alignmentGroups.find(g=>g.alignmentGroupId===f.nativeScaleGroupId);const al=s.alignments[f.frameVersionId];const w=g?.cell.width||512,h=g?.cell.height||512;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const c=canvas.getContext('2d')!;c.imageSmoothingEnabled=false;const im=await loadImage(a.url);const scale=g?.sharedScale??1;const anchor=al?.contactMode==='airborne'?(al.rootAnchor||al.sourceAnchor):al?.sourceAnchor;const x=Math.floor((g?.targetAnchor.x??0)-scale*(anchor?.x??0)+(al?.authoredOffsetPx.x??0)+0.5),y=Math.floor((g?.targetAnchor.y??0)-scale*(anchor?.y??0)+(al?.authoredOffsetPx.y??0)+0.5);c.drawImage(im,x,y,Math.round(im.width*scale),Math.round(im.height*scale));
 for(const p of o.pixelEdits||[]){c.clearRect(p.x,p.y,1,1);if(p.color[3]){c.fillStyle=`rgba(${p.color[0]},${p.color[1]},${p.color[2]},${p.color[3]/255})`;c.fillRect(p.x,p.y,1,1);}}
 const transformed=document.createElement('canvas');transformed.width=w;transformed.height=h;const t=transformed.getContext('2d')!;t.imageSmoothingEnabled=false;const tr={...defaultTransform(),...o.transform,pivot:o.transform.pivot||{x:w/2,y:h/2}};t.translate(tr.pivot.x+tr.dx,tr.pivot.y+tr.dy);t.rotate(-tr.rotationDeg*Math.PI/180);t.transform(1,tr.shearY,tr.shearX,1,0,0);t.scale(tr.scaleX*(tr.flipX?-1:1),tr.scaleY*(tr.flipY?-1:1));t.translate(-tr.pivot.x,-tr.pivot.y);t.drawImage(canvas,0,0);
 if(outline&&s.outline.enabled){const out=document.createElement('canvas');out.width=w;out.height=h;const oc=out.getContext('2d')!;const silhouette=document.createElement('canvas');silhouette.width=w;silhouette.height=h;const sc=silhouette.getContext('2d')!;sc.drawImage(transformed,0,0);sc.globalCompositeOperation='source-in';const col=s.outline.colorRGBA;sc.fillStyle=`rgba(${col[0]},${col[1]},${col[2]},${col[3]/255})`;sc.fillRect(0,0,w,h);oc.globalAlpha=s.outline.opacityPerCopy;const d=s.outline.thicknessPx;const dirs=[[d,0],[-d,0],[0,d],[0,-d],...(s.outline.directions===8?[[d,d],[d,-d],[-d,d],[-d,-d]]:[])];dirs.forEach(([dx,dy])=>oc.drawImage(silhouette,dx,dy));oc.globalAlpha=1;oc.drawImage(transformed,0,0);return out;}
 return transformed;
}
export function occurrenceAt(durations:number[],elapsed:number,loop:boolean):number{const total=durations.reduce((a,b)=>a+b,0);if(!total)return -1;let t=loop?elapsed%total:Math.min(elapsed,total-0.00001);for(let i=0;i<durations.length;i++){if(t<durations[i])return i;t-=durations[i];}return durations.length-1;}
export function validateRuntime(v:unknown):Runtime {const r=v as Runtime;if(!r||r.schemaVersion!==1||!r.atlas||!Array.isArray(r.frames)||!Array.isArray(r.clips))throw new Error('지원하는 runtime.json 형식(schemaVersion 1)이 아닙니다.');if(!r.clips.length||!r.frames.length)throw new Error('재생할 프레임 또는 동작이 없습니다.');const ids=new Set(r.frames.map(f=>f.id));for(const f of r.frames){const p=f.rect;if(!p||![p.x,p.y,p.width,p.height].every(Number.isFinite)||p.width<=0||p.height<=0||p.x<0||p.y<0||p.x+p.width>r.atlas.width||p.y+p.height>r.atlas.height)throw new Error('아틀라스 프레임 영역이 올바르지 않습니다.');}for(const c of r.clips){if(c.endBehavior!=='hold-last')throw new Error('이 뷰어는 마지막 프레임 유지 방식만 지원합니다.');if(!c.occurrences.length)throw new Error('빈 재생 순서가 포함되어 있습니다.');for(const o of c.occurrences)if(!ids.has(o.renderedFrameId)||!Number.isInteger(o.durationMs)||o.durationMs<1||o.durationMs>60000)throw new Error('프레임 참조 또는 표시 시간이 올바르지 않습니다.');}return r;}
