import {useState,useEffect,useId,isValidElement,cloneElement,type ReactElement,type ReactNode,type InputHTMLAttributes,type SelectHTMLAttributes} from 'react';
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label>{isValidElement(children)?cloneElement(children as ReactElement<any>,{id,'aria-describedby':hint?`${id}-hint`:undefined}):children}{hint&&<small id={`${id}-hint`} aria-live="polite">{hint}</small>}</div>}
export function Num({label,value,onChange,min,max,step=1,hint}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;hint?:string}){const [text,setText]=useState(String(value)),[error,setError]=useState('');useEffect(()=>setText(String(value)),[value]);function commit(){const v=Number(text);if(!text.trim()||!Number.isFinite(v)||(min!==undefined&&v<min)||(max!==undefined&&v>max)||(step===1&&!Number.isInteger(v))){setError(`유효한 ${step===1?'정수':'숫자'}${min!==undefined?` (${min} 이상)`:''}${max!==undefined?` (${max} 이하)`:''}를 입력하세요.`);return;}setError('');if(v!==value)onChange(v);}return <Field label={label} hint={error||hint}><input type="number" required value={text} min={min} max={max} step={step} aria-invalid={!!error} onChange={e=>setText(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.currentTarget.blur();}if(e.key==='Escape'){setText(String(value));setError('');}}}/></Field>}
export function Input({label,...props}:InputHTMLAttributes<HTMLInputElement>&{label:string}){return <Field label={label}><input {...props}/></Field>}
export function Select({label,children,...props}:SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <Field label={label}><select {...props}>{children}</select></Field>}
export function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
export function Panel({title,eyebrow,children,actions}:{title:string;eyebrow?:string;children:ReactNode;actions?:ReactNode}){return <section className="panel"><div className="panel-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{actions}</div>{children}</section>}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><div className="empty-glyph" aria-hidden="true">▧</div><h3>{title}</h3>{children}</div>}
export const short=(id:string|undefined|null)=>id?.slice(0,8)||'없음';
export const date=(v:string)=>new Date(v).toLocaleString('ko-KR');
